AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub OAuth Lambda for SlideRule Web Client - Organization Membership Verification'

Parameters:
  GitHubClientId:
    Type: String
    Description: GitHub OAuth App Client ID

  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: Environment (test or prod)

  FrontendUrl:
    Type: String
    Default: https://testsliderule.org
    Description: Frontend URL for redirects after OAuth

  LambdaS3Bucket:
    Type: String
    Default: sliderule-lambda-deployments
    Description: S3 bucket containing the Lambda deployment package

  LambdaS3Key:
    Type: String
    Default: github-oauth.zip
    Description: S3 key for the Lambda deployment package

Resources:
  # Note: GitHub Client Secret must be created manually in Secrets Manager before deploying:
  #   aws secretsmanager create-secret --name sliderule/github-oauth-client-secret-test --secret-string "YOUR_SECRET"
  #   aws secretsmanager create-secret --name sliderule/github-oauth-client-secret-prod --secret-string "YOUR_SECRET"

  # Secrets Manager - Auto-generate JWT Signing Key
  # This secret is shared between the Lambda and SlideRule server
  JWTSigningKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'sliderule/github-oauth-jwt-signing-key-${Environment}'
      Description: JWT signing key for SlideRule GitHub OAuth tokens (auto-generated)
      GenerateSecretString:
        PasswordLength: 64
        ExcludePunctuation: true
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: sliderule-web-client

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      # Note: RoleName removed to avoid iam:GetRole permission requirement
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  # Reference existing GitHub client secret (created manually)
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:sliderule/github-oauth-client-secret-${Environment}*'
                  - !Ref JWTSigningKeySecret
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: sliderule-web-client

  # Lambda Function
  GitHubOAuthLambda:
    Type: AWS::Lambda::Function
    Properties:
      # Note: FunctionName removed to let CloudFormation auto-generate
      Description: !Sub 'GitHub OAuth handler for SlideRule Web Client (${Environment})'
      Runtime: python3.12
      Handler: handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Environment:
        Variables:
          GITHUB_CLIENT_ID: !Ref GitHubClientId
          GITHUB_ORG: SlideRuleEarth
          FRONTEND_URL: !Ref FrontendUrl
          # Reference existing secret by name (must be created manually before deploying)
          CLIENT_SECRET_NAME: !Sub 'sliderule/github-oauth-client-secret-${Environment}'
          JWT_SIGNING_KEY_ARN: !Ref JWTSigningKeySecret
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: sliderule-web-client

  # API Gateway HTTP API
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'sliderule-github-oauth-${Environment}'
      Description: GitHub OAuth API for SlideRule Web Client
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - !Ref FrontendUrl
          - 'http://localhost:5173'
          - 'http://localhost:5174'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300
      Tags:
        Environment: !Ref Environment
        Application: sliderule-web-client

  # API Gateway Integration with Lambda
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GitHubOAuthLambda.Arn
      PayloadFormatVersion: '2.0'

  # Route: GET /auth/github/login
  LoginRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /auth/github/login'
      Target: !Sub 'integrations/${LambdaIntegration}'

  # Route: GET /auth/github/callback
  CallbackRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /auth/github/callback'
      Target: !Sub 'integrations/${LambdaIntegration}'

  # Route: POST /auth/github/device (Device Flow - request device code)
  DeviceCodeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /auth/github/device'
      Target: !Sub 'integrations/${LambdaIntegration}'

  # Route: POST /auth/github/device/poll (Device Flow - poll for token)
  DevicePollRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /auth/github/device/poll'
      Target: !Sub 'integrations/${LambdaIntegration}'

  # API Gateway Stage (auto-deploy)
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true
      Tags:
        Environment: !Ref Environment
        Application: sliderule-web-client

  # Lambda Permission for API Gateway
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GitHubOAuthLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !GetAtt HttpApi.ApiEndpoint
    Export:
      Name: !Sub 'sliderule-github-oauth-api-url-${Environment}'

  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt GitHubOAuthLambda.Arn
    Export:
      Name: !Sub 'sliderule-github-oauth-lambda-arn-${Environment}'

  ClientSecretName:
    Description: GitHub Client Secret name in Secrets Manager (must be created manually)
    Value: !Sub 'sliderule/github-oauth-client-secret-${Environment}'

  JWTSigningKeySecretArn:
    Description: JWT Signing Key Secret ARN (Secrets Manager) - use this in your server to validate tokens
    Value: !Ref JWTSigningKeySecret
    Export:
      Name: !Sub 'sliderule-github-oauth-jwt-signing-key-arn-${Environment}'

  JWTSigningKeySecretName:
    Description: JWT Signing Key Secret Name - use this to retrieve the key
    Value: !Sub 'sliderule/github-oauth-jwt-signing-key-${Environment}'
