import type {
    SrRegion,
    Atl13,
    SrListNumberItem,
    SrListStringItem,
    SrMultiSelectNumberItem,
    SrMenuItem,
} from '@/types/SrTypes';

export interface SrReqParamsState {
    missionValue: string;
    iceSat2SelectedAPI: string;
    gediSelectedAPI: string;
    using_worker: boolean;
    isFeatherStream: boolean;
    rasterizePolyCellSize: number;
    ignorePolygon: boolean;
    poly: SrRegion | null;
    convexHull: SrRegion | null;
    areaOfConvexHull: number;
    urlValue: string;
    enableGranuleSelection: boolean;
    tracks: SrListNumberItem[];
    selectAllTracks: boolean;
    beams: SrListNumberItem[];
    selectAllBeams: boolean;
    useRGT: boolean;
    rgtValue: number;
    useCycle: boolean;
    cycleValue: number;
    useRegion: boolean;
    regionValue: number;
    useTime: boolean;
    gpsToUTCOffset: number;
    minDate: Date;
    t0Value: Date;
    t1Value: Date;
    useServerTimeout: boolean;
    serverTimeoutValue: number;
    useReqTimeout: boolean;
    reqTimeoutValue: number;
    useNodeTimeout: boolean;
    nodeTimeoutValue: number;
    useReadTimeout: boolean;
    readTimeoutValue: number;
    useLength: boolean;
    lengthValue: number;
    useStep: boolean;
    stepValue: number;
    confidenceValue: number;
    iterationsValue: number;
    spreadValue: number;
    PE_CountValue: number;
    windowValue: number;    
    enableAtl03Classification: boolean;
    surfaceReferenceType: SrMultiSelectNumberItem[];
    signalConfidence: SrMultiSelectNumberItem[];
    qualityPH: SrMultiSelectNumberItem[];
    enableAtl08Classification: boolean;
    atl08LandType: string[];
    distanceIn: SrMenuItem;
    passInvalid: boolean;
    useAlongTrackSpread: boolean;
    alongTrackSpread: number;
    useMinimumPhotonCount: boolean;
    minimumPhotonCount: number;
    useSurfaceFitAlgorithm: boolean;
    maxIterations: number;
    useMaxIterations: boolean;
    minWindowHeight: number;
    useMinWindowHeight: boolean;
    maxRobustDispersion: number;
    useMaxRobustDispersion: boolean;
    gediBeams: number[];
    degradeFlag: boolean;
    l2QualityFlag: boolean;
    l4QualityFlag: boolean;
    surfaceFlag: boolean;
    fileOutput: boolean;
    staged: boolean;
    fileOutputFormat: SrMenuItem;
    outputLocation: SrListStringItem;
    outputLocationPath: string;
    awsRegion: SrListStringItem;
    enableYAPC: boolean;
    useYAPCScore: boolean;
    YAPCScore: number;
    usesYAPCKnn: boolean;
    YAPCKnn: number;
    usesYAPCMinKnn: boolean;
    YAPCMinKnn: number;
    usesYAPCWindowHeight: boolean;
    YAPCWindowHeight: number;
    usesYAPCWindowWidth: boolean;
    YAPCWindowWidth: number;
    usesYAPCVersion: boolean;
    YAPCVersion: number;
    resources: string[];
    useChecksum: boolean;
    enableAtl24Classification: boolean;
    defaultsFetched: boolean;
    useDatum: boolean;
    useAtl24Compact: boolean;
    atl24Compact: boolean;
    useAtl24Classification: boolean;
    atl24_class_ph: string[];
    useAtl24ConfidenceThreshold: boolean;
    atl24ConfidenceThreshold: number;
    useAtl24InvalidKD: boolean;
    atl24InvalidKD: string[];
    useAtl24InvalidWindspeed: boolean;
    atl24InvalidWindspeed: string[];
    useAtl24LowConfidence: boolean;
    atl24LowConfidence: string[];
    useAtl24Night: boolean;
    atl24Night: string[];
    useAtl24SensorDepthExceeded: boolean;
    atl24SensorDepthExceeded: string[];
    atl24AncillaryFields: string[];
    atl03AncillaryFields: string[];
    atl08AncillaryFields: string[];
    atl03_geo_fields: string[];
    atl03_corr_fields: string[];
    atl03_ph_fields: string[];
    atl06_fields: string[];
    atl08_fields: string[];
    atl13_fields: string[];
    gedi_fields: string[];
    useAtl13RefId: boolean;
    atl13: Atl13;
    enablePhoReal: boolean;
    usePhoRealBinSize: boolean;
    phoRealBinSize: number;
    usePhoRealGeoLocation: boolean;
    phoRealGeoLocation: string;
    usePhoRealAbsoluteHeights: boolean;
    usePhoRealSendWaveforms: boolean;
    usePhoRealABoVEClassifier: boolean;
    useAtl13Polygon: boolean;
    useAtl13Point: boolean;
    forcedAddedParams: Record<string, unknown>,
    forcedRemovedParams: string[],
    showParamsDialog: boolean;
}
