#!/usr/bin/env bash
# Refresh tests/data/docs-anchors.json from the live docs site.
#
# The snapshot is what tests/unit/docLinks.spec.ts checks src/utils/docLinks.ts
# against, so run this after the docs site restructures — then fix any link the
# spec reports as pointing at a page or anchor that no longer exists.
set -euo pipefail
cd "$(dirname "$0")"

curl -fsSL https://docs.slideruleearth.io/myst.xref.json | python3 -c '
import collections, datetime, json, sys

refs = json.load(sys.stdin)["references"]
pages = collections.defaultdict(set)
for ref in refs:
    url = ref.get("url")
    if not url:
        continue
    pages[url]
    if ref.get("kind") == "heading" and ref.get("identifier"):
        pages[url].add(ref["identifier"])

json.dump(
    {
        "_comment": "Snapshot of the pages and heading anchors published by docs.slideruleearth.io. Regenerated by tests/data/regen-docs-anchors.sh.",
        "_source": "https://docs.slideruleearth.io/myst.xref.json",
        "_captured": datetime.date.today().isoformat(),
        "pages": {k: sorted(v) for k, v in sorted(pages.items())},
    },
    sys.stdout,
    indent=1,
)
' > docs-anchors.json

echo "wrote $(pwd)/docs-anchors.json"
